# Integer Linear Programming Solver

Optimization Problem: Select 10 articles to display on the news feed that must have 
- More-than-average number of images, videos, and links
- At least two 'Others' articles to balance dominancee of other common topics
- At least three different categories are displayed

In [35]:
import pandas as pd 
import numpy as np
import os
import pulp

import sys
sys.path.append('/workspaces/news-promotion-lp')
from src.data.preprocess import load_data, preprocess_features
from src.optimization.lp_solver import news_solver, extended_news_solver

## Dataset process

We will use the test dataset with predicted shares as input for the solver.

In [36]:
df_lp = pd.read_csv("../data/processed/lp_coefficients.csv")
df_lp.head()

,data_channel_is_lifestyle,data_channel_is_entertainment,data_channel_is_bus,data_channel_is_socmed,data_channel_is_tech,data_channel_is_world,data_channel_is_other,weekday_is_monday,weekday_is_tuesday,weekday_is_wednesday,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,pred_shares
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.072069,0.172098,0.773899,0.076074,0.376707,-0.871396,-0.266541,0.838354,-0.689110,7.421087
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.586949,0.978078,0.799087,0.936944,0.077773,-0.871396,-0.266541,0.838354,-0.689110,7.290183
2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,3.965849,-1.036872,-1.316659,-1.645667,-0.837712,-0.871396,-0.266541,0.838354,-0.689110,7.633775
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,5.735748,-1.036872,0.335451,0.936944,-0.619740,0.361687,-1.203750,-1.282312,0.410682,7.454219
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.072069,-0.633882,0.060255,0.076074,0.077773,-0.254855,-0.641425,-0.221979,-0.249193,7.318145

In [37]:
shares = df_lp["pred_shares"].to_numpy()
lifestyle_indicator = df_lp[" data_channel_is_lifestyle"].to_numpy()
entertainment_indicator = df_lp[" data_channel_is_entertainment"].to_numpy()
bus_indicator = df_lp[" data_channel_is_bus"].to_numpy()
socmed_indicator = df_lp[" data_channel_is_socmed"].to_numpy()
tech_indicator = df_lp[" data_channel_is_tech"].to_numpy()
world_indicator = df_lp[" data_channel_is_world"].to_numpy()
other_indicator = df_lp[" data_channel_is_other"].to_numpy()

## Solver Implementation

In [38]:
def news_solver(
        shares,
        lifestyle_indicator,
        entertainment_indicator,
        bus_indicator,
        socmed_indicator,
        tech_indicator,
        world_indicator,
        other_indicator,
        K=10,
        lower_bound=0,
        solver_name="PULP_CBC_CMD",
        verbose=False
):
    """
    Build ILP model for news article selection that maximize shares and maintain topic diversity.

    Parameters
    ----------
    popularity : array-like, shape (N,)
        (Predicted) raw shares
    *_indicator : array-like, shape (N,)
        1 if article is classified as each in the category list, 0 otherwise
    K : int
        Number of articles to select
    
    Return
    ----------
    selected_indices: list
        List of selected optimal indices
    status: str
        Solver status
    """
    N = len(shares)
    
    # Model
    model = pulp.LpProblem("News Selection", pulp.LpMaximize)
    
    # Decision Variables
    x = pulp.LpVariable.dicts("select", range(N), cat="Binary")

    # Objective
    model += pulp.lpSum(
        (shares[i] * x[i] for i in range(N)))

    # Capacity constraints
    model += pulp.lpSum(x[i] for i in range(N)) == K

    # Topic constraints 
    model += pulp.lpSum(lifestyle_indicator[i] * x[i] for i in range(N)) >= lower_bound
    model += pulp.lpSum(entertainment_indicator[i] * x[i] for i in range(N)) >= lower_bound
    model += pulp.lpSum(bus_indicator[i] * x[i] for i in range(N)) >= lower_bound
    model += pulp.lpSum(socmed_indicator[i] * x[i] for i in range(N)) >= lower_bound
    model += pulp.lpSum(tech_indicator[i] * x[i] for i in range(N)) >= lower_bound
    model += pulp.lpSum(world_indicator[i] * x[i] for i in range(N)) >= lower_bound
    model += pulp.lpSum(other_indicator[i] * x[i] for i in range(N)) >= lower_bound

    # Choose solver
    if solver_name == "PULP_CBC_CMD":
        solver = pulp.PULP_CBC_CMD(msg=verbose)
    else:
        raise ValueError(f"Unsupported Solver:{solver_name}")
    
    # Solve
    model.solve(solver)

    status = pulp.LpStatus[model.status]

    if status != "Optimal":
        print(f"Warning: Solver status = {status}")
    
    # Extract solution
    selected_indices = [
        i for i, var in x.items() if var.value() == 1
    ]
    return selected_indices, status

In [39]:
selected_indices, status = news_solver(
        shares=shares,
        lifestyle_indicator=lifestyle_indicator,
        entertainment_indicator=entertainment_indicator,
        bus_indicator=bus_indicator,
        socmed_indicator=socmed_indicator,
        tech_indicator=tech_indicator,
        world_indicator=world_indicator,
        other_indicator=other_indicator,
)

print(f"List of articles selected: {selected_indices}")

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

List of articles selected: [583, 1096, 2669, 3202, 5024, 5319, 6347, 6886, 7344, 7498]

In [42]:
df_lp

,data_channel_is_lifestyle,data_channel_is_entertainment,data_channel_is_bus,data_channel_is_socmed,data_channel_is_tech,data_channel_is_world,data_channel_is_other,weekday_is_monday,weekday_is_tuesday,weekday_is_wednesday,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,pred_shares
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.072069,0.172098,0.773899,0.076074,0.376707,-0.871396,-0.266541,0.838354,-0.689110,7.421087
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.586949,0.978078,0.799087,0.936944,0.077773,-0.871396,-0.266541,0.838354,-0.689110,7.290183
2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,3.965849,-1.036872,-1.316659,-1.645667,-0.837712,-0.871396,-0.266541,0.838354,-0.689110,7.633775
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,5.735748,-1.036872,0.335451,0.936944,-0.619740,0.361687,-1.203750,-1.282312,0.410682,7.454219
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.072069,-0.633882,0.060255,0.076074,0.077773,-0.254855,-0.641425,-0.221979,-0.249193,7.318145
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7924,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.586949,0.172098,0.596654,0.764770,-0.183794,-0.871396,-0.266541,0.838354,-0.689110,7.773231
7925,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,-0.871878,-0.230892,0.324568,0.420422,0.600908,-0.871396,-0.266541,0.838354,-0.689110,7.431555
7926,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.458901,0.978078,-1.301938,-1.645667,0.862475,-0.871396,-0.266541,0.838354,-0.689110,7.041371
7927,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.072069,0.978078,-0.361091,0.076074,0.077773,-0.871396,-0.266541,0.838354,-0.689110,7.568172
7928,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.072069,-0.029397,0.084406,-0.268274,0.600908,-0.871396,-0.266541,0.838354,-0.689110,7.430340

In [45]:
lp_shares = df_lp.iloc[selected_indices]['pred_shares'].sum()
print(f"Optimal Shares by Linear Programming: {lp_shares: .2f} shares")

Optimal Shares by Linear Programming:  86.87 shares